[package]
name = "yarrow"
version = "0.1.0"
authors = ["Billy Messenger <60663878+BillyDM@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
keywords = ["gui", "audio"]
categories = ["gui", "visualization"]
description = "A retained-mode GUI library in Rust with extreme performance and control, geared towards audio software"
homepage = "https://github.com/MeadowlarkDAW/Yarrow"
documentation = "https://docs.rs/yarrow"
repository = "https://github.com/MeadowlarkDAW/Yarrow"
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["winit", "x11", "wayland", "winit-wayland-dlopen", "winit-wayland-csd-adwaita"]
x11 = ["winit?/x11"]
wayland = ["winit?/wayland"]
winit-wayland-dlopen = ["winit?/wayland-dlopen"]
winit-wayland-csd-adwaita = ["winit?/wayland-csd-adwaita"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.3"
log = "0.4.20"
rustc-hash = "1.1.0"
smallvec = "1.13.1"
thunderdome = "0.6.1"
unicode-segmentation = "1.11.0"
keyboard-types = { version = "0.7.0", default-features = false }
raw-window-handle = { version = "0.6.0", features = ["std"] }
winit = { version = "0.30.0", optional = true, default-features = false, features = ["rwh_06"] }
wgpu = { version = "0.20.0", default-features = false, features = ["wgsl"] }
window_clipboard = "0.4.1"
rootvg = { git = "https://github.com/MeadowlarkDAW/rootvg", rev = "02faef85948bc7411edf4b86475ee3595bcd1b3f" }
#rootvg = { path = "../rootvg" }

[dev-dependencies]
env_logger = { version = "0.11.3", default-features = false }
derive_more = "0.99.17"