[package]
name = "yarrow"
version = "0.1.0"
authors = ["Billy Messenger <60663878+BillyDM@users.noreply.github.com>"]
edition = "2021"
license = "MIT"
keywords = ["gui", "audio"]
categories = ["gui", "visualization"]
description = "A modern retained-mode GUI library in Rust with extreme performance and control, geared towards audio software"
homepage = "https://github.com/MeadowlarkDAW/Yarrow"
documentation = "https://docs.rs/yarrow"
repository = "https://github.com/MeadowlarkDAW/Yarrow"
readme = "README.md"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = [
    "gradient",
    "mesh",
    "tessellation",
    "msaa",
    "svg-icons",
    "web-colors",
    "baseview",
    "x11",
    "wayland",
    "winit-wayland-csd-adwaita",
]
# Enables gradient support
# If your app doesn't use gradients, then disabling this may slightly improve performance and memory usage.
gradient = ["rootvg/gradient"]
# Enables drawing of images/textures (required by some elements)
image = ["rootvg/image"]
# Enables drawing meshes of triangles (required by some elements)
mesh = ["rootvg/mesh"]
# Enables using the lyon crate to tessellate vector shapes into a mesh for rendering (required by some elements)
tessellation = ["mesh", "rootvg/tessellation"]
# Enables anti-aliasing of mesh primitives using MSAA. Note this only affects mesh primitives, so consider
# disabling this if your app does not use them.
msaa = ["rootvg/msaa"]
# Enables rendering svg icons (required by some elements)
svg-icons = ["rootvg/svg-icons"]
# Enables broken "sRGB linear" blending to reproduce color management of the Web.
# Recommended for better text legibility.
# See: https://github.com/iced-rs/iced/pull/1888
#      https://github.com/pop-os/cosmic-text/issues/195
web-colors = ["rootvg/web-colors"]
# Enables X11 support on Linux platforms
x11 = ["winit?/x11"]
# Enables Wayland support on Linux platforms
wayland = ["winit?/wayland"]
# Enables adwaita client-side window decorations when using winit and Wayland
winit-wayland-csd-adwaita = ["winit?/wayland-csd-adwaita"]
# Enables serde support for some types
serde = ["dep:serde", "rootvg/serde"]

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["yarrow_derive"]

[dependencies]
yarrow_derive = { path = "yarrow_derive" }
bitflags = "2.3.3"
log = "0.4.20"
rustc-hash = "2.0.0"
ahash = "0.8.11"
smallvec = "1.13.1"
thunderdome = "0.6.1"
unicode-segmentation = "1.11.0"
keyboard-types = { version = "0.6.1", default-features = false }
raw-window-handle = { version = "0.5.0", features = ["std"] }
raw-window-handle-06 = { package = "raw-window-handle", version = "0.6.0" }
winit = { version = "0.30.0", optional = true, default-features = false, features = [
    "rwh_06",
] }
baseview = { git = "https://github.com/RustAudio/baseview.git", optional = true }
wgpu = { version = "22", default-features = false, features = ["wgsl"] }
window_clipboard = "0.4.1"
thiserror = "1.0.61"
serde = { version = "1.0", default-features = false, features = [
    "derive",
], optional = true }
rootvg = { git = "https://github.com/MeadowlarkDAW/rootvg", rev = "a98b6addb26f68345330cbb1f80313f5571ba9a1", default-features = false, features = [
    "quad",
    "text",
    "default-surface",
] }

[dev-dependencies]
wgpu = { version = "22", default-features = true }
env_logger = { version = "0.11.3", default-features = false }
derive_more = { version = "1.0", features = ["display"] }

[profile.dev]
opt-level = 1 # Laying out text can be really slow without optimizations.
